project:
  type: website

website:
  title: "Justin Powley"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects_upcoming.qmd

format:
  html:
    theme: cosmo
    css: styles.css
#    toc: true

editor: visual
title-block: false

